language: node_js
node_js:
    - "stable"
sudo: false
install:
  - npm install -g purescript pulp bower
  - npm install
  - bower install
after_success:
  - >-
    test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push

